# Atividade 03 - 09/11/23

Documentação Numpy: https://numpy.org/doc/stable/

Enviar este arquivo preenchido com as respostas e o nome do aluno para o e-mail: profbrunorespostas1@gmail.com e assunto: AD2303

Prazo: 14/11/23

Pontos: 20

### Orientações

- Usar apenas a biblioteca pandas para responder as questões desta atividade;
- Utilizar o dataset disponibilizado no Google Sala de Aula com o título: DATASET - ATIVIDADE PANDAS - 01;
- O dataset trata de aparições de ovnis pelo mundo e foi retirado da plataforma Kaggle.

In [ ]:
#Substituir nome do aluno aqui
print("Márcio Fernando Lopes da Silva")

In [1]:
import pandas as pd

In [2]:
dataframe_u = pd.read_table('ufo.csv', sep=',')
dataframe_u

,Unnamed: 0,Date_time,date_documented,Year,Month,Hour,Season,Country_Code,Country,Region,Locale,latitude,longitude,UFO_shape,length_of_encounter_seconds,Encounter_Duration,Description
0,0,1949-10-10 20:30:00,4/27/2004,1949,10,20,Autumn,USA,United States,Texas,San Marcos,29.883056,-97.941111,Cylinder,2700.0,45 minutes,This event took place in early fall around 194...
1,1,1949-10-10 21:00:00,12/16/2005,1949,10,21,Autumn,USA,United States,Texas,Bexar County,29.384210,-98.581082,Light,7200.0,1-2 hrs,1949 Lackland AFB&#44 TX. Lights racing acros...
2,2,1955-10-10 17:00:00,1/21/2008,1955,10,17,Autumn,GBR,United Kingdom,England,Chester,53.200000,-2.916667,Circle,20.0,20 seconds,Green/Orange circular disc over Chester&#44 En...
3,3,1956-10-10 21:00:00,1/17/2004,1956,10,21,Autumn,USA,United States,Texas,Edna,28.978333,-96.645833,Circle,20.0,1/2 hour,My older brother and twin sister were leaving ...
4,4,1960-10-10 20:00:00,1/22/2004,1960,10,20,Autumn,USA,United States,Hawaii,Kaneohe,21.418056,-157.803611,Light,900.0,15 minutes,AS a Marine 1st Lt. flying an FJ4B fighter/att...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80323,80323,2013-09-09 21:15:00,9/30/2013,2013,9,21,Autumn,USA,United States,Tennessee,Nashville,36.165833,-86.784444,Light,600.0,10 minutes,Round from the distance/slowly changing colors...
80324,80324,2013-09-09 22:00:00,9/30/2013,2013,9,22,Autumn,USA,United States,Idaho,Boise,43.613611,-116.202500,Circle,1200.0,20 minutes,Boise&#44 ID&#44 spherical&#44 20 min&#44 10 r...
80325,80325,2013-09-09 22:00:00,9/30/2013,2013,9,22,Autumn,USA,United States,California,Napa Abajo,38.297222,-122.284444,Other,1200.0,hour,Napa UFO&#44
80326,80326,2013-09-09 22:20:00,9/30/2013,2013,9,22,Autumn,USA,United States,Virginia,Vienna,38.901111,-77.265556,Circle,5.0,5 seconds,Saw a five gold lit cicular craft moving fastl...
80327,80327,2013-09-09 23:00:00,9/30/2013,2013,9,23,Autumn,USA,United States,Oklahoma,Edmond,35.652778,-97.477778,Cigar,1020.0,17 minutes,2 witnesses 2 miles apart&#44 Red &amp; White...

### Questão 1

Imprimir apenas as 15 primeiras linhas do dataset.

In [7]:
dataframe_u[:15]

,Unnamed: 0,Date_time,date_documented,Year,Month,Hour,Season,Country_Code,Country,Region,Locale,latitude,longitude,UFO_shape,length_of_encounter_seconds,Encounter_Duration,Description
0,0,1949-10-10 20:30:00,4/27/2004,1949,10,20,Autumn,USA,United States,Texas,San Marcos,29.883056,-97.941111,Cylinder,2700.0,45 minutes,This event took place in early fall around 194...
1,1,1949-10-10 21:00:00,12/16/2005,1949,10,21,Autumn,USA,United States,Texas,Bexar County,29.384210,-98.581082,Light,7200.0,1-2 hrs,1949 Lackland AFB&#44 TX. Lights racing acros...
2,2,1955-10-10 17:00:00,1/21/2008,1955,10,17,Autumn,GBR,United Kingdom,England,Chester,53.200000,-2.916667,Circle,20.0,20 seconds,Green/Orange circular disc over Chester&#44 En...
3,3,1956-10-10 21:00:00,1/17/2004,1956,10,21,Autumn,USA,United States,Texas,Edna,28.978333,-96.645833,Circle,20.0,1/2 hour,My older brother and twin sister were leaving ...
4,4,1960-10-10 20:00:00,1/22/2004,1960,10,20,Autumn,USA,United States,Hawaii,Kaneohe,21.418056,-157.803611,Light,900.0,15 minutes,AS a Marine 1st Lt. flying an FJ4B fighter/att...
5,5,1961-10-10 19:00:00,4/27/2007,1961,10,19,Autumn,USA,United States,Tennessee,Bristol,36.595000,-82.188889,Sphere,300.0,5 minutes,My father is now 89 my brother 52 the girl wit...
6,6,1965-10-10 21:00:00,2/14/2006,1965,10,21,Autumn,GBR,United Kingdom,Wales,Penarth,51.434722,-3.180000,Circle,180.0,about 3 mins,penarth uk circle 3mins stayed 30ft above m...
7,7,1965-10-10 23:45:00,10/2/1999,1965,10,23,Autumn,USA,United States,Connecticut,Norwalk,41.117500,-73.408333,Disk,1200.0,20 minutes,A bright orange color changing to reddish colo...
8,8,1966-10-10 20:00:00,3/19/2009,1966,10,20,Autumn,USA,United States,Alabama,Harrisburg,33.586111,-86.286111,Disk,180.0,3 minutes,Strobe Lighted disk shape object observed clos...
9,9,1966-10-10 21:00:00,5/11/2005,1966,10,21,Autumn,USA,United States,Florida,Live Oak,30.294722,-82.984167,Disk,120.0,several minutes,Saucer zaps energy from powerline as my pregna...
10,10,1968-10-10 13:00:00,10/31/2003,1968,10,13,Autumn,USA,United States,California,Hawthorne,33.916389,-118.351667,Circle,300.0,5 min.,ROUND &#44 ORANGE &#44 WITH WHAT I WOULD SAY W...
11,11,1968-10-10 19:00:00,6/12/2008,1968,10,19,Autumn,USA,United States,North Carolina,Franklin Park,35.233333,-82.734444,Fireball,180.0,3 minutes,silent red /orange mass of energy floated by t...
12,12,1970-10-10 16:00:00,5/11/2000,1970,10,16,Autumn,USA,United States,New York,Nassau County,40.668611,-73.527500,Disk,1800.0,30 min.,silver disc seen by family and neighbors
13,13,1970-10-10 19:00:00,2/14/2008,1970,10,19,Autumn,USA,United States,Kentucky,Manchester,37.153611,-83.761944,Unknown,180.0,3 minutes,Slow moving&#44 silent craft accelerated at an...
14,14,1971-10-10 21:00:00,2/14/2010,1971,10,21,Autumn,USA,United States,North Carolina,South Cecil,35.823889,-80.253611,Oval,30.0,30 seconds,green oval shaped light over my local church&#...

### Questão 2

Imprimir apenas as aparições que ocorreram no ano de 2014.

In [9]:
dataframe_u[dataframe_u.Year == 2014]

,Unnamed: 0,Date_time,date_documented,Year,Month,Hour,Season,Country_Code,Country,Region,Locale,latitude,longitude,UFO_shape,length_of_encounter_seconds,Encounter_Duration,Description
7612,7612,2014-01-10 06:00:00,1/16/2014,2014,1,6,Winter,USA,United States,California,Placentia,33.872222,-117.869444,Rectangle,60.0,~1 minute,EXTRATERRESTRIAL MULTICOLOR SPACECRAFT OVER GO...
7613,7613,2014-01-10 06:15:00,1/16/2014,2014,1,6,Winter,USA,United States,Texas,El Paso,31.758611,-106.486389,Circle,120.0,~2 minutes,Single round&#44 reddish yellowish&#44 greenis...
7614,7614,2014-01-10 06:30:00,1/10/2014,2014,1,6,Winter,USA,United States,Colorado,Coal Creek,38.361111,-105.147778,Sphere,1200.0,20 minutes,Large&#44 yellowish white reflective sphere wi...
7615,7615,2014-01-10 09:57:00,2/14/2014,2014,1,9,Winter,USA,United States,Connecticut,Parkville,41.763611,-72.685556,Flash,120.0,2 minute,((HOAX??)) While i was watching a movie a whit...
7616,7616,2014-01-10 16:30:00,1/16/2014,2014,1,16,Winter,GBR,United Kingdom,England,Barrowford,53.845000,-2.204000,Light,900.0,15 minutes,A light hovered down the hill at a ridiculous ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46150,46150,2014-05-07 21:10:00,5/8/2014,2014,5,21,Spring,USA,United States,Connecticut,Naugatuck,41.485833,-73.051111,Unknown,300.0,5 minutes,Large formation of lights in western sky&#44 f...
46151,46151,2014-05-07 21:20:00,5/8/2014,2014,5,21,Spring,USA,United States,Missouri,Hillsboro,38.232222,-90.562778,Fireball,360.0,4-6 minutes,Round slow moving silent ball looked like a ca...
46152,46152,2014-05-07 23:30:00,5/8/2014,2014,5,23,Spring,USA,United States,New Mexico,San Ysidro,35.563363,-106.770591,Unknown,15.0,15 seconds,2 red lights gliding across sky&#44 then green...
46298,46298,2014-05-08 00:00:00,5/8/2014,2014,5,0,Spring,USA,United States,Tennessee,Lauderdale Courts,35.149444,-90.048889,Rectangle,900.0,15 minutes,Standing at my window around 0:00 brilliantly ...
46299,46299,2014-05-08 18:45:00,5/8/2014,2014,5,18,Spring,AUS,Australia,Victoria,Inverloch,-38.626591,145.722595,Light,300.0,5 minutes,Bright orange light travelling above inverloch...

### Questão 3

Imprimir apenas as aparições que ocorreram no ano de 2011 e no Brasil (Country_Code)

In [54]:
dataframe_u.loc[dataframe_u.Year == 2011, 'Country_Code']

230      USA
231      USA
232      USA
233      USA
234      GBR
        ...
80279    USA
80280    USA
80281    USA
80282    USA
80283    USA
Name: Country_Code, Length: 5107, dtype: object

### Questão 4

Imprimir as aparições que ocorreram no Estado do Rio Grande do Norte ou da Paraíba (Region).

In [59]:
dataframe_u.loc['Region']

KeyError: 'Region'

### Questão 5

Imprimir as aparições que ocorreram entre os anos de 2000 e 2014 nos Estados Unidos.

### Questão 6

Imprimir todas aparições que ocorreram no ano de 2010 e que não foram no formato de Triângulo (UFO_shape)

### Questão 7

Imprimir as aparições que ocorreram entre as datas 01/01/2011 e 30/07/2011 (utilizando a coluna Date_time).

Obs.: Pesquisar como converter os textos da coluna Date_time para o formato correto de data no Pandas, para que se possa realizar os cálculos.

### Questão 8

Imprimir a quantidade de aparições que ocorreram por cada país.

Obs.: Pesquisar sobre agrupamento através da função groupby() e como contar através da função count().

### Questão 9

Utilizando a questão anterior, imprimir ordenando do país com maior aparições para o com menor.

### Questão 10

Utilizando a questão anterior, retornar apenas os 5 países com as maiores quantidades de aparições.